config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'frontpage#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/' => 'frontpage#index', as: :frontpage
    get '/team' => 'frontpage#team'
    get '/share_callback' => 'frontpage#share_callback'
    resources :activities, :only => [:show, :index]
    resources :projects, :only => [:show, :index]
    resources :profiles, :only => [:show, :index]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  translates :name, :card_info, :feat_heading, :feat_lead, :tag, :credit

  has_many :project_sections
  has_many :project_relations, foreign_key: 'parent_id'
  has_many :related_projects, through: :project_relations, source: :child

  has_many :popup_images, as: :popup_imageable

  accepts_nested_attributes_for :project_relations

  extend FriendlyId
  friendly_id :slugged_url, use: [:slugged, :history]

  active_admin_translates :name, :card_info, :feat_heading, :feat_lead, :tag, :credit
  accepts_nested_attributes_for :project_sections, :allow_destroy => true
  accepts_nested_attributes_for :project_relations, :allow_destroy => true

  accepts_nested_attributes_for :popup_images, allow_destroy: true

  mount_uploader :card_image, CardImageUploader

  default_scope -> { order(:position, :updated_at) }


  # before_validation :set_project_section_position

  def should_generate_new_friendly_id?
    slug.blank? || slugged_url_changed?
  end

  def set_project_section_positions!

    if project_sections.size > 0
      positions = project_sections.map { |item| item.position }

      max_position = positions.max { |p1, p2| p1 <=> p2 }
      max_position = max_position + 10

      project_sections.each do |section|
        if section.position == 0
          section.update_attribute(:position, max_position)
          max_position = max_position + 10
        end
      end

    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]
  before_action :show_projects_menu, only: [:index]

  def index
    @section_title = I18n.t('menu.projects')
  end

  def show
    @section_title = @project.name
    render :layout => 'project'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.where(visible: true).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project]
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.slim
= title 'Проекты Мастерской'

.container-fluid
  .dbm-content-wrapper
    .dbm-content
      .dbm-content-inner
        .dbm-text-flow
          ul.activities-list
            - for project in @projects
              li.activities-list-item
                a.activities-list-item-img href="#{project_path(project)}"
                  img.img-anons width='100%' height='auto' alt='' src="#{project.card_image.big_1280x1280.url}"
                a.activities-list-item-heading href="#{project_path(project)}"
                  | #{project.feat_heading}
                .activities-list-item-tag
                  | #{project.card_info}

app/views/projects/show.html.slim
= title "#{@project.feat_heading}"

= content_for :additional_meta do
  meta property="og:type" content='website'
  meta property="og:url" content="#{project_url(@project)}"
  meta property="og:title" content="#{strip_tags(decode(@project.feat_heading))}"
  meta property="og:description" content="#{strip_tags(decode(@project.feat_lead))}"
  - if @project.card_image
    meta property="og:image" content="#{@project.card_image.url}"

.container-fluid
  .dbm-content-wrapper
    .dbm-content
      .dbm-content-inner
        - unless @project.feat_heading.blank?
          .dbm-text-flow
            h1 = @project.feat_heading
        - unless @project.feat_lead.blank?
          .dbm-text-flow
            .lead
              = @project.feat_lead.html_safe

        - @project.project_sections.each_with_index do |project_section, index |
          - unless project_section.name.blank?
            .dbm-text-flow
              h2 = project_section.name
          - unless project_section.subheading.blank?
            .dbm-text-flow
              h3 = project_section.subheading
          - unless project_section.section_text.blank?
            .dbm-text-flow
              = project_section.section_text.try(:html_safe)
          - if project_section.vimeo_video_str.blank?
            - project_section.project_section_images.each_with_index do |project_section_image , idx |
              .dbm-img-flow
                .dbm-img-flow-container
                  img.dbm-img-post src="#{project_section_image.image_url}" width="100%" height="auto"
                  - if index == 0 && idx == 0
                    .credit.credit-rotate
                      | #{@project.credit}
                - unless project_section_image.caption.blank?
                  .row
                    .dbm-text-flow
                      .caption = project_section_image.caption.try(:html_safe)

          - else
            .dbm-img-flow
              .dbm-img-post
                .embed-responsive.embed-responsive-16by9
                  iframe src="//player.vimeo.com/video/#{project_section.vimeo_video_str}" webkitallowfullscreen='' mozallowfullscreen='' allowfullscreen=''


        .dbm-img-flow.last
          .footer
            .col-sm-2.col-md-3.hidden-xs
              .h2
                = render 'layout_partials/nav_brand_locales'

            .col-sm-4.col-md-3
              h2
                | Поделиться
              ul.social-likes.list-unstyled.share-buttons
                li.facebook data={app_id: "#{Settings.social.fb_app_id}", callback_url: "#{share_callback_url}"} Facebook
                li.twitter Twitter
                li.vkontakte Вконтакте

        - unless @project.related_projects.blank?
          .dbm-text-flow
            h2 Другие проекты
            ul.activities-list
              - for related_project in @project.related_projects
                li.activities-list-item
                  a.activities-list-item-img href="#{project_path(related_project)}"
                    img.img-anons width='100%' height='auto' alt='' src="#{related_project.card_image.big_1280x1280.url}"
                  a.activities-list-item-heading href="#{project_path(related_project)}"
                    | #{related_project.feat_heading}
                  .activities-list-item-tag
                    | #{related_project.card_info}


= content_for :page_javascripts do
  javascript:
    $(document).ready(function(){
      $('.social-likes').socialLikes({
        url: '#{project_url(@project)}',
        title: '#{@project.feat_heading}',
        counters: true
      });
    });