config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'frontpage#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/' => 'frontpage#index', as: :frontpage
    get '/team' => 'frontpage#team'
    get '/share_callback' => 'frontpage#share_callback'
    resources :activities, :only => [:show, :index]
    resources :projects, :only => [:show, :index]
    resources :profiles, :only => [:show, :index]
  end

end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  layout 'application'

  def index
    main_project = Project.where(:shown_on_main => true).reorder('RANDOM()').first
    # main_activity = Activity.where(:shown_on_main => true).first
    @main_page_content = DynamicContent.main_page
    @main_page_object = main_project
  end

  def team

  end

  def share_callback

  end

end

app/views/frontpage/index.en.html.slim
= title 'Мастерская Димы Барбанеля'

= content_for :additional_meta do
  meta property="og:type" content='website'
  meta property="og:url" content="#{frontpage_url}"
  meta property="og:title" content='Мастерская Димы Барбанеля'
  meta property="og:description" content='Мастерская Димы Барбанеля'
  meta property="og:image" content="#{image_url('m-logo.png')}"


.content-wrapper
  .content
    .content-text
      - if @main_page_content.present?
        strong
          = @main_page_content.content.html_safe
      - else
        p
          strong
            | Мастерская <sup></sup> — междисциплинарная
            a href="#{profiles_path}"
              |  проектная группа
            |. Мы&nbsp;способны формулировать и&nbsp;решать социально значимые проектные задачи через исследование и&nbsp;переосмысление контекста.

        p
          strong
            a href='mailto: ask@masterskaya.pro'
              | ask@masterskaya.pro
            br/
            | +7 916 903 41 38

    - if @main_page_object

      a.content-img href="#{link_to_project_or_activity(@main_page_object)}"
        .content-img-inner style="background-image: url(#{@main_page_object.card_image.big_1280x1280.url})"
      .credit.credit-rotate
        | #{@main_page_object.credit}

app/views/frontpage/index.html.slim
p
  strong
    | Мастерская <sup></sup> — междисциплинарная
    a href="/team/"
      |  проектная группа
    |. Мы способны формулировать и решать социально значимые проектные задачи через исследование и переосмысление контекста
  
p
  strong
    a href="mailto: ask@masterskaya.pro"
      | ask@masterskaya.pro
    br/
    | +7 915 077 6823
      
.img-anons-main
  img.img-anons src="#{image_path('activities/polytype-main.jpg')}"

app/views/frontpage/index.ru.html.slim
= title 'Мастерская Димы Барбанеля'

= content_for :additional_meta do
  meta property="og:type" content='website'
  meta property="og:url" content="#{frontpage_url}"
  meta property="og:title" content='Мастерская Димы Барбанеля'
  meta property="og:description" content='Мастерская Димы Барбанеля'
  meta property="og:image" content="#{image_url('m-logo.png')}"


.content-wrapper
  .content
    .content-text
      - if @main_page_content.present?
        strong
          = @main_page_content.content.html_safe
      - else
        p
          strong
            | Мастерская <sup></sup> — междисциплинарная
            a href="#{profiles_path}"
              |  проектная группа
            |. Мы&nbsp;способны формулировать и&nbsp;решать социально значимые проектные задачи через исследование и&nbsp;переосмысление контекста.

        p
          strong
            a href='mailto: ask@masterskaya.pro'
              | ask@masterskaya.pro
            br/
            | +7 916 903 41 38

    - if @main_page_object

      a.content-img href="#{link_to_project_or_activity(@main_page_object)}"
        .content-img-inner style="background-image: url(#{@main_page_object.card_image.big_1280x1280.url})"
      .credit.credit-rotate
        | #{@main_page_object.credit}

app/views/frontpage/share_callback.html.slim
javascript:
  self.close();

app/views/frontpage/team.en.html.slim
h1
  | Team

app/views/frontpage/team.ru.html.slim
= title 'Команда Мастерской'

.container-fluid
  .dbm-content-wrapper
    .dbm-content
      .dbm-content-inner
        .dbm-text-flow

          h1.page-heading
            strong
              | Команда

          ul.list-inline.list-team
            li
              ul.list-unstyled.strong
                li
                  a href='http://dimabarbanel.com/' Дима Барбанель
                  br/
                  | Визуальные коммуникации
                li
                  a href='mailto: alexashin@masterskaya.pro' Дмитрий Алексашин
                  br/
                  | Управление проектами
                li
                  a href='mailto: olga@masterskaya.pro' Оля Смирнова
                  br/
                  | Мастерская кадров
                  br/
                  | Развитие
                  br/
                  | PR
                li
                  a href='https://www.facebook.com/gorbachev.viktor' Виктор Горбачев
                  br/
                  | Кино
                  br/
                  | Фото
                li
                  a href='https://www.facebook.com/dimaevgrafov' Дмитрий Евграфов
                  br/
                  | Музыка
                li
                  a href='https://www.facebook.com/jenyakaff' Евгений Евграфов
                  br/
                  | Видео
                li
                  a href='#' Сергей Калинин
                  br/
                  | Иллюстрации
                li
                  a href='http://campusrussia.com/program/' Федор Кноков
                  br/
                  | Преподавание
                  br/
                  | Методика
                li
                  a href='https://www.facebook.com/konstantin.lukjanov.3' Константин Лукьянов
                  br/
                  | Типографика
                  li
                    a href='https://www.facebook.com/roman.manikhin' Роман Манихин
                    br/
                    | Иллюстрации

            li
              ul.list-unstyled.strong
                li
                  a href='https://www.facebook.com/sergey.mozhaykin' Сергей Можайкин
                  br/
                  | Преподавание
                  br/
                  | Методика
                li
                  a href='https://www.facebook.com/sergei.monakhov' Сергей Монахов
                  br/
                  | Редактирование
                li
                  a href='https://www.facebook.com/svyatoslavponomarev' Святослав Пономарев
                  br/
                  | Преподавание
                  br/
                  | Методика
                li
                  a href='http://campusrussia.com/program/' Антон Терехов
                  br/
                  | Типографика
                  br/
                  | История
                  br/
                  | Архив
                li
                  a href='https://www.facebook.com/anton.fedorov.351' Антон Федоров
                  br/
                  | Экспозиционный дизайн
                li
                  a href='https://www.facebook.com/sergey.fedorov.94' Сергей Федоров
                  br/
                  | Интерфейс
                li
                  a href='https://www.facebook.com/zhdan.philippov' Ждан Филиппов
                  br/
                  | Макетирование
                li
                  a href='https://www.facebook.com/maxishilov' Макс Шилов
                  br/
                  | Брендинг
                li
                  a href='https://www.facebook.com/eugene.yukechev' Евгений Юкечев
                  br/
                  | Типографика
                  br/
                  | Type Journal