config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'frontpage#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/' => 'frontpage#index', as: :frontpage
    get '/team' => 'frontpage#team'
    get '/share_callback' => 'frontpage#share_callback'
    resources :activities, :only => [:show, :index]
    resources :projects, :only => [:show, :index]
    resources :profiles, :only => [:show, :index]
  end

end

app/views/layout_partials/_activity_menu_list.html.slim
- if defined? activities
  ul.list-unstyled class="#{list_class}"
    - for activity in activities
      li
        - if current_activity && (current_activity.id == activity.id)
          a.nav-inner.active href="#{activity_path(activity)}" = activity.name
        - else
          a.nav-inner href="#{activity_path(activity)}" = activity.name

app/views/layout_partials/_fb_init_script.html.slim
javascript:
  window.fbAsyncInit = function () {
    FB.init({
      appId: "#{Settings.social.fb_app_id}",
      xfbml: true,
      version: 'v2.0'
    });
  };

  (function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {
      return;
    }
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  function postToFeed(title, desc, url, image) {
    var obj = {method: 'feed', link: url, picture: image, name: title, description: desc};

    function callback(response) {
    }

    FB.ui(obj, callback);
  }

  $(document.body).on('click', '.fb-share', function (event) {
    event.preventDefault();
    var elem = $(this);
    postToFeed(elem.data('title'), elem.data('desc'), elem.prop('href'), elem.data('image'));
    return false;
  });

app/views/layout_partials/_nav_activities.html.slim
ul.dbm-navbar-nav
  li
    a.strong href="#{activities_path}"
      | #{I18n.t('menu.activities')}
    - if @show_activities
      = render partial: 'layout_partials/activity_menu_list', locals: { activities: @activities, current_activity: @activity, list_class: 'menu' }
    = render partial: 'layout_partials/activity_menu_list', locals: { activities: @activities, current_activity: @activity, list_class: 'hamburger-menu' }

app/views/layout_partials/_nav_brand.html.slim
.nav-brand
  = render 'layout_partials/nav_brand_locales'

app/views/layout_partials/_nav_brand_locales.html.slim
- if I18n.locale == :ru
  a href="/"
    img src="#{image_path('m-logo.svg')}"
  .nav-brand-lang
    a href="#{url_for({locale: :en})}"
      img src="#{image_path('en.svg')}"
- else
  a href="/en"
    img src="#{image_path('m-logo-en.svg')}"
  .nav-brand-lang
    a href="#{url_for({locale: :ru})}"
      img src="#{image_path('ru.svg')}"

app/views/layout_partials/_nav_projects.html.slim
ul.dbm-navbar-nav
  li
    a.strong href="#{projects_path}"
      | #{I18n.t('menu.projects')}
    - if @show_projects
      = render partial: 'layout_partials/projects_menu_list', locals: { projects: @projects, list_class: 'menu' }
    = render partial: 'layout_partials/projects_menu_list', locals: { projects: @projects, list_class: 'hamburger-menu' }

app/views/layout_partials/_projects_menu_list.html.slim
- if defined? projects
  ul.list-unstyled class="#{list_class}"
    - for project in projects
      li
        a.nav-inner href="#{project_path(project)}" = project.name