config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'frontpage#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/' => 'frontpage#index', as: :frontpage
    get '/team' => 'frontpage#team'
    get '/share_callback' => 'frontpage#share_callback'
    resources :activities, :only => [:show, :index]
    resources :projects, :only => [:show, :index]
    resources :profiles, :only => [:show, :index]
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  has_many :gallery_images, as: :gallery_imageable

  extend FriendlyId

  friendly_id :slugged_url, use: [:slugged, :history]

  translates :name, :heading, :description, :link, :link_text, :credit
  active_admin_translates :name, :heading, :description, :link, :link_text, :credit


  mount_uploader :attachment, UnchangedNameUploader
  mount_uploader :card_image, CardImageUploader
  mount_uploader :preview_video_image, GalleryImageUploader

  default_scope -> { order(:position, :updated_at)}


  accepts_nested_attributes_for :gallery_images, allow_destroy: true

  def should_generate_new_friendly_id?
    slug.blank? || slugged_url_changed?
  end


  def first_gallery_image
    gallery_images.first
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show]
  before_action :show_activities_menu


  def index
    @section_title = I18n.t('menu.activities')
  end

  def show
    @section_title = @activity.name
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.friendly.where(visible: true).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_params
    params[:activity]
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.slim
= title 'Инициативы Мастерской'

.container-fluid
  .dbm-content-wrapper
    .dbm-content
      .dbm-content-inner
        .dbm-text-flow
          ul.activities-list
            - for activity in @activities
              li.activities-list-item
                a.activities-list-item-img href="#{activity_path(activity)}"
                  img.img-anons width='100%' height='auto' alt='' src="#{activity.card_image.big_1280x1280.url}"
                a.activities-list-item-heading href="#{activity_path(activity)}"
                  | #{activity.heading}

app/views/activities/show.html.slim
= title "#{@activity.heading}"

= content_for :additional_meta do
  meta property="og:type" content='website'
  meta property="og:url" content="#{activity_url(@activity)}"
  meta property="og:title" content="#{strip_tags(decode(@activity.heading))}"
  meta property="og:description" content="#{strip_tags(decode(@activity.description))}"
  /- if @project.card_image
    meta property="og:image" content="#{@project.card_image.url}"


.content-wrapper
  .content
    .content-text
      h1.h3
        | #{@activity.heading}
      p
        | #{@activity.description.html_safe}

      ul.list-inline
        - unless @activity.attachment.file.blank?
          li
            a href="#{@activity.attachment.url}"
              | #{@activity.attachment.file.filename}
            |  #{number_to_human_size(@activity.attachment.file.size, {precision: 0})}
        li
          a href="#{@activity.link}"
            | #{@activity.link_text}

    .content-img
      - if @activity.vimeo_video_str.blank?
        - if @activity.gallery_images.size > 0
          - if @activity.gallery_images.size > 1
            #carousel.slide data-ride="carousel"
              .carousel-inner
                - first = true
                - for gallery_image in @activity.gallery_images
                  .item class="#{first ? 'active' : ''}"
                    .content-img-inner style="background-image: url(#{gallery_image.image.try(:big_1280x1280).try(:url)})"
                  - first = false
          - else
            .content-img-inner style="background-image: url(#{@activity.gallery_images.first.image.try(:big_1280x1280).try(:url)})"


      - else
        .content-img-inner style="background-image: url(#{@activity.preview_video_image.try(:big_1280x1280).try(:url)})"

    .credit.credit-rotate
      | #{@activity.credit}